(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



PilchWarner::usage="This package imports the geoMetric.m package.
This package has some general features:
1. Independent of signature and coordinate indexing.
	signature = 1 (mostly minus, ?metric for more information), coordLabel (with SU(2) Maurer-Cartan forms) and coordNDLabel (a version of Euler parametrization of the Maurer-Cartan forms) are the default. 
	Note: the name of the coordinates are hard-coded!
2. The expressions are general in both r and c coordinates, hence rc is used.
	Evaluate PWc or PWr in order to use the rules defined for the coordinate. Analogous rules: 
		cRule <-> rRule
		ARule <-> c\[Rho]Rule1 and c\[Rho]Rule2
3. F1Rules, F3Rules, F5Rules are defined. 
	Use F1[name][i], F3[name][i,j,k] and F5[name][i,j,k,l,m], where name is the name of the form field. In this way, only the non-vanishing components appear, but in a HoldForm way. 
	Time efficiency tip: Replace Rule to Set in the rules, then apply ReleaseHold to the HoldForm components. 
";


AppendTo[$Path,ToFileName[{NotebookDirectory[]}]];
<<geoMetric.m


Clear[x0,x1,x2,x3,rc,\[Theta],\[Phi],\[Sigma]1,\[Sigma]2,\[Sigma]3]
coordLabel=<|
x0-> 1,x1-> 2,x2-> 3,x3-> 4,rc-> 5,
\[Theta]-> 6,\[Sigma]1-> 7,\[Sigma]2-> 8,\[Sigma]3->9,\[Phi]->10
|>;

coordNDLabel=<|
x0-> 1,x1-> 2,x2-> 3,x3-> 4,rc-> 5,
\[Theta]-> 6,\[Alpha]-> 7,\[Beta]-> 8,\[Psi]->9,\[Phi]->10
|>;

(*coordLabel\[Phi]7=<|
x0\[Rule] 1,x1\[Rule] 2,x2\[Rule] 3,x3\[Rule] 4,rc\[Rule] 5,
\[Theta]\[Rule] 6,\[Sigma]1\[Rule] 8,\[Sigma]2\[Rule] 9,\[Sigma]3\[Rule]10,\[Phi]\[Rule]7
|>;*) (*Be careful with parity transformations!*)

signature=1; (* Mostly minus, i.e (+, -, -, -,...), check ?metric *)

$Assumptions=vrc[rc,\[Theta]]>= 0&&vx[rc,\[Theta]]>= 0&&v\[Theta][rc,\[Theta]]>= 0&&v\[Phi][rc,\[Theta]]>= 0&&v1[rc,\[Theta]]>= 0&&v2[rc,\[Theta]]>= 0&&Reals[c,\[Theta]] && c>= 1 &&c[rc]>= 1&&A[c]>= 1&&X1[rc,\[Theta]]>= 0&&X2[rc,\[Theta]]>= 0(*&&\[Pi]/2\[GreaterEqual] \[Theta]\[GreaterEqual] 0*)(* It gives problems when take limit \[Theta]\[Rule]\[Pi]/2 *);

vielbeinD:=Module[{EE},
EE[coordLabel[x0]]=EE[coordLabel[x1]]=EE[coordLabel[x2]]=EE[coordLabel[x3]]=vx[rc,\[Theta]];
EE[coordLabel[rc]]=vrc[rc,\[Theta]];
EE[coordLabel[\[Theta]]]=v\[Theta][rc,\[Theta]];
EE[coordLabel[\[Phi]]]=v\[Phi][rc,\[Theta]];
EE[coordLabel[\[Sigma]1]]=v1[rc,\[Theta]];
EE[coordLabel[\[Sigma]2]]=EE[coordLabel[\[Sigma]3]]=v2[rc,\[Theta]];
DiagonalMatrix[Array[EE,10]]
];
inVielbeinD:=Inverse@vielbeinD;

coordND:=Keys[coordNDLabel];
vielbeinND:=Module[{EE3Sphere,aa,aaNew},
EE3Sphere=\!\(\*
TagBox[
RowBox[{"(", "", GridBox[{
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"v1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], 
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{"v1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], "0"},
{"0", 
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Sin", "[", "\[Alpha]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{"v2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], 
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Alpha]", "]"}], " ", 
RowBox[{"v2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{"0", 
RowBox[{
RowBox[{"-", 
FractionBox["1", "2"]}], " ", 
RowBox[{"Cos", "[", "\[Alpha]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{"v2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], 
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Sin", "[", "\[Alpha]", "]"}], " ", 
RowBox[{"v2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}
},
GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}], "", ")"}],
Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\);

aa=ArrayRules@EE3Sphere;
aaNew=aa[[;;,1]]/.{1-> coordNDLabel[\[Alpha]],2-> coordNDLabel[\[Beta]],3-> coordNDLabel[\[Psi]]};
aa[[;;,1]]=aaNew;

Normal@SparseArray[
Join[{
{coordLabel[x0],coordLabel[x0]}-> vx[rc,\[Theta]],
{coordLabel[x1],coordLabel[x1]}-> vx[rc,\[Theta]],
{coordLabel[x2],coordLabel[x2]}-> vx[rc,\[Theta]],
{coordLabel[x3],coordLabel[x3]}-> vx[rc,\[Theta]],
{coordLabel[rc],coordLabel[rc]}-> vrc[rc,\[Theta]],
{coordLabel[\[Theta]],coordLabel[\[Theta]]}-> v\[Theta][rc,\[Theta]],
{coordLabel[\[Phi]],coordLabel[\[Phi]]}-> v\[Phi][rc,\[Theta]]},
aa]
]
];
vielbeinND::usage=" Euler parametrization for the SU(2) forms, see coordND.
vielbeinND[[a,\[Mu]]] \[Equal] \!\(\*SubsuperscriptBox[\(E\), \(\[Mu]\), \(a\)]\), where a is the local frame index and \[Mu] is the target space index.";

inVielbeinND:=Inverse@vielbeinND;


clearForms:=Clear[F5RR, F5RRlocal,F3RR,F3RRlocal,F3RREuler, H,Hlocal,HEuler,F1RR,F1RRlocal,P,Pcc,Plocalcc,Plocal,Q,Qlocal]
clearForms


F5list:=Module[{
list={coordLabel/@{x0,x1,x2,x3,rc},coordLabel/@{x0,x1,x2,x3,\[Theta]}},
hodge
},
hodge=hodgeDual[1,list[[#]],metric[0][vielbeinD]]&/@{1,2}; (* Independent of the metric signature as any signs are absorbed into the coefficient *)
Join[list,hodge[[;;,2]]
]
];

coefF5RR:=Module[{
coef={D[\[Omega][rc,\[Theta]],rc],D[\[Omega][rc,\[Theta]],\[Theta]]},
hodge
},
hodge=FullSimplify@hodgeDual[coef[[#]],F5list[[#]],metric[signature][vielbeinD]]&/@{1,2};
Join[coef,signOrientation hodge[[;;,1]]] (*The sign is negative for c coordinate, since dc/dr<0. It's defined in cRule and rRule.*)
]


F5Rules:=Module[{
productInV=(Times@@(inVielbeinD[[#,#]]&/@{##})&@@@F5list),
coefLocal},
coefLocal=productInV*coefF5RR;
{listsToRule[F5RR@@@Sort/@F5list,coefF5RR*Signature/@F5list ],listsToRule[F5RRlocal@@@Sort/@F5list,coefLocal*Signature/@F5list]}
]

F5[name_][i_?IntegerQ, j_?IntegerQ, k_?IntegerQ, l_?IntegerQ, m_?IntegerQ]:=formSkeleton[name][F5list][i,j,k,l,m]
F5::usage= "F5[name][i,j,k,l,m] gives the component of the 5 forms, but as HoldForm of name[i,j,k,l,m]. ";
F5RRtilde[i__]:=4F5RR[i]


(* 3-forms: F3RR, H, G3 and G3^* *)
F3list:=Map[coordLabel,#]&/@{{\[Sigma]2,\[Sigma]3,\[Phi]},{\[Sigma]2,\[Sigma]3,\[Theta]},{\[Sigma]1,\[Theta],\[Phi]},{\[Sigma]1,rc,\[Theta]},{\[Sigma]2,\[Sigma]3,rc},{\[Sigma]1,rc,\[Phi]}};
coefF3RR=(\!\(\*
TagBox[GridBox[{
{
RowBox[{
RowBox[{"-", 
RowBox[{"(", 
RowBox[{
RowBox[{"a2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{"2", " ", 
RowBox[{"a3", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}], ")"}]}], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}]}]},
{
RowBox[{
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"2", " ", 
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], "-", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
RowBox[{"-", 
RowBox[{"Sin", "[", "\[Phi]", "]"}]}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"-", 
RowBox[{"Sin", "[", "\[Phi]", "]"}]}], " ", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"-", 
RowBox[{"Cos", "[", "\[Phi]", "]"}]}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}
},
GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.5599999999999999]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}],
Column]\));coefH=(\!\(\*
TagBox[GridBox[{
{
RowBox[{
RowBox[{"-", 
RowBox[{"(", 
RowBox[{
RowBox[{"a2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{"2", " ", 
RowBox[{"a3", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}], ")"}]}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}]}]},
{
RowBox[{
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{
RowBox[{"-", "2"}], " ", 
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], "+", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"-", 
RowBox[{"Sin", "[", "\[Phi]", "]"}]}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}
},
GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.5599999999999999]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}],
Column]\));

F3Rules:=Module[{global,local,productInV=Times@@(inVielbeinD[[#,#]]&/@{##})&@@@F3list},
(* Global frame *)
global=Join[listsToRule[F3RR@@@Sort/@F3list,coefF3RR* Signature/@F3list ],
listsToRule[H@@@Sort/@F3list,coefH *Signature/@F3list]];

(* Local frame (diagonal) *)
local=Join[listsToRule[F3RRlocal@@@Sort/@F3list,productInV*coefF3RR*Signature/@F3list],
listsToRule[Hlocal@@@Sort/@F3list,productInV*coefH*Signature/@F3list]];
{global,local}
]

F3[name_][i_Integer,j_Integer,k_Integer]:=formSkeleton[name][F3list][i,j,k]

G3[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],\[Phi]])F3RR[i,j,k]+I (1+B[rc,\[Theta],\[Phi]])H[i,j,k])
G3cc[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],-\[Phi]])F3RR[i,j,k]-I (1+B[rc,\[Theta],-\[Phi]])H[i,j,k])

G3local[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],\[Phi]])F3RRlocal[i,j,k]+I (1+B[rc,\[Theta],\[Phi]])Hlocal[i,j,k])
G3localcc[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],-\[Phi]])F3RRlocal[i,j,k]-I (1+B[rc,\[Theta],-\[Phi]])Hlocal[i,j,k])


F3EulerList:=Map[coordNDLabel,#]&/@{{\[Beta],\[Phi],\[Psi]},{\[Beta],\[Theta],\[Psi]},{\[Alpha],\[Theta],\[Phi]},{\[Beta],\[Theta],\[Phi]},{rc,\[Alpha],\[Theta]},{rc,\[Beta],\[Theta]},{rc,\[Beta],\[Psi]},{rc,\[Alpha],\[Phi]},{rc,\[Beta],\[Phi]}};
coefF3RREuler=\!\(\*
TagBox[
RowBox[{"(", "", 
TagBox[GridBox[{
{
RowBox[{
FractionBox["1", "4"], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{"2", " ", 
RowBox[{"a3", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}], ")"}], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}]}]},
{
RowBox[{
RowBox[{"-", 
FractionBox["1", "4"]}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"2", " ", 
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], "-", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"-", 
FractionBox["1", "4"]}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}
},
GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.5599999999999999]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}],
Column], "", ")"}],
Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\);coefHEuler=\!\(\*
TagBox[
RowBox[{"(", "", 
TagBox[GridBox[{
{
RowBox[{
FractionBox["1", "4"], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a2", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{"2", " ", 
RowBox[{"a3", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}], ")"}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}]}]},
{
RowBox[{
FractionBox["1", "4"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"2", " ", 
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], "-", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{"(", 
RowBox[{
RowBox[{"a1", "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}], "-", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}], ")"}]}]},
{
RowBox[{
RowBox[{"-", 
FractionBox["1", "2"]}], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
RowBox[{"-", 
FractionBox["1", "2"]}], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a1", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "4"], " ", 
RowBox[{"Cos", "[", "\[Phi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Psi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a2", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]},
{
RowBox[{
FractionBox["1", "2"], " ", 
RowBox[{"Cos", "[", "\[Psi]", "]"}], " ", 
RowBox[{"Sin", "[", "\[Phi]", "]"}], " ", 
RowBox[{
SuperscriptBox["a3", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None], "[", 
RowBox[{"rc", ",", "\[Theta]"}], "]"}]}]}
},
GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.5599999999999999]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}],
Column], "", ")"}],
Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\);
(* Global frame *)
F3EulerRules:=Join[
listsToRule[F3RREuler@@@Sort/@F3EulerList,coefF3RREuler* Signature/@F3EulerList],listsToRule[HEuler@@@Sort/@F3EulerList,coefHEuler *Signature/@F3EulerList]
]

F3Euler[name_][i_Integer,j_Integer,k_Integer]:=formSkeleton[name][F3EulerList][i,j,k]

G3Euler[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],\[Phi]])F3RREuler[i,j,k]+I (1+B[rc,\[Theta],\[Phi]])HEuler[i,j,k])
G3Eulercc[i_?IntegerQ,j_?IntegerQ,k_?IntegerQ]:=f[rc,\[Theta]]( (1-B[rc,\[Theta],-\[Phi]])F3RREuler[i,j,k]-I (1+B[rc,\[Theta],-\[Phi]])HEuler[i,j,k])


(* 1-forms: F1RR, P, P^* and Q *)
expDilaton[rc_,\[Theta]_,\[Phi]_]:=(1-2 b[rc,\[Theta]] Cos[2\[Phi]]+b[rc,\[Theta]]^2)/(1-b[rc,\[Theta]]^2)  (* \[ExponentialE]^\[CapitalPhi] *)

\[Chi][rc_,\[Theta]_,\[Phi]_]:=-((2  b[rc,\[Theta]] Sin[2\[Phi]])/(1-2 b[rc,\[Theta]] Cos[2\[Phi]]+b[rc,\[Theta]]^2))

F1list:=Map[coordLabel,#]&/@{{rc},{\[Theta]},{\[Phi]}}
coefF1RR={D[\[Chi][rc,\[Theta],\[Phi]],rc],D[\[Chi][rc,\[Theta],\[Phi]],\[Theta]],D[\[Chi][rc,\[Theta],\[Phi]],\[Phi]]}//FullSimplify//Expand;
coefP=f[rc,\[Theta]]^2 {D[B[rc,\[Theta],\[Phi]],rc],D[B[rc,\[Theta],\[Phi]],\[Theta]],D[B[rc,\[Theta],\[Phi]],\[Phi]]}//FullSimplify//Expand;
(* Psar is the complex conjugate of P *)
coefPcc=f[rc,\[Theta]]^2 {D[B[rc,\[Theta],-\[Phi]],rc],D[B[rc,\[Theta],-\[Phi]],\[Theta]],D[B[rc,\[Theta],-\[Phi]],\[Phi]]}//FullSimplify//Expand;
coefQ={ 0,0,-2 f[rc,\[Theta]]^2 b[rc,\[Theta]]^2}//FullSimplify //Expand;

F1Rules:=Module[
{global,local,productInV=Times@@(inVielbeinD[[#,#]]&/@{##})&@@@F1list},

global=Join[
listsToRule[F1RR@@@F1list,coefF1RR],
listsToRule[P@@@F1list,coefP],
listsToRule[Pcc@@@F1list,coefPcc],
listsToRule[Q@@@F1list,coefQ]
];

local=Join[
listsToRule[F1RRlocal@@@F1list,productInV*coefF1RR],
listsToRule[Plocal@@@F1list,productInV*coefP],
listsToRule[Plocalcc@@@F1list,productInV*coefPcc],
listsToRule[Qlocal@@@F1list,productInV*coefQ]
];
{global,local}
]

F1[name_][i_Integer]:=If[
ToString@name=="Q"||ToString@name=="Qlocal",
formSkeleton[name][{Last@F1list}][i],
formSkeleton[name][F1list][i]
]


PWr:=Module[{},
clearPWr;

rRule:={rc->r,signOrientation->  signature * 1 (* transformation of Levi-Civita tensor *)};
vRule ={
vx-> Function[{r,\[Theta]},\[Rho][r]^(3/2)/Sqrt[c[r]^2-1] (c[r]X2[r,\[Theta]]X1[r,\[Theta]])^(1/8)],
vrc-> Function[{r,\[Theta]},1/\[Rho][r]^(1/2) (c[r]X1[r,\[Theta]]X2[r,\[Theta]])^(1/8)],
v\[Theta]-> Function[{r,\[Theta]},1/\[Rho][r]^(3/2) ((X2[r,\[Theta]]X1[r,\[Theta]])/c[r]^3)^(1/8)],
v\[Phi]-> Function[{r,\[Theta]},1/\[Rho][r]^(3/2) ((c[r]X1[r,\[Theta]])/X2[r,\[Theta]]^3)^(1/8) Sin[\[Theta]]],
v1-> Function[{r,\[Theta]},\[Rho][r]^(3/2) (X1[r,\[Theta]]/(c[r]^3 X2[r,\[Theta]]^3))^(1/8) Cos[\[Theta]]],
v2-> Function[{r,\[Theta]},\[Rho][r]^(3/2) ((c[r]X2[r,\[Theta]])/X1[r,\[Theta]]^3)^(1/8) Cos[\[Theta]]]
};

formsRules={
b->Function[{r,\[Theta]},(Sqrt[c[r] X1[r,\[Theta]]]-Sqrt[X2[r,\[Theta]]])/(Sqrt[c[r] X1[r,\[Theta]]]+Sqrt[X2[r,\[Theta]]])],
B->Function[{r,\[Theta],\[Phi]},b[r,\[Theta]]E^(I 2\[Phi])],
f->Function[{r,\[Theta]},1/Sqrt[1-b[r,\[Theta]]^2]],


\[Omega]->Function[{r,\[Theta]},(\[Rho][r]^6 X1[r,\[Theta]])/(4 (-1+c[r]^2)^2)],
a1->Function[{r,\[Theta]},-(Sqrt[c[r]^2-1]/c[r])Cos[\[Theta]]],
a2->Function[{r,\[Theta]}, \[Rho][r]^6 Sqrt[c[r]^2-1]/X1[r,\[Theta]] Sin[\[Theta]]Cos[\[Theta]]^2],
a3->Function[{r,\[Theta]},-(Sqrt[c[r]^2-1]/X2[r,\[Theta]])Sin[\[Theta]]Cos[\[Theta]]^2]
};

X1X2Rule={
X1->Function[{r,\[Theta]},Cos[\[Theta]]^2+c[r] \[Rho][r]^6 Sin[\[Theta]]^2],
X2->Function[{r,\[Theta]},c[r] Cos[\[Theta]]^2+\[Rho][r]^6 Sin[\[Theta]]^2]
};
c\[Rho]Rule1={Derivative[2][c][r_]-> D[\[Rho][r]^4 (1-c[r]^2),r],Derivative[2][\[Rho]][r_]->D[ 1/3 (1/\[Rho][r]-c[r]\[Rho][r]^5),r]};
(*Note that Mathematica interprested wrongly c'' as Power[c,'']!*)
c\[Rho]Rule2={Derivative[1][c][r_]-> \[Rho][r]^4 (1-c[r]^2),Derivative[1][\[Rho]][r_]-> 1/3 (1/\[Rho][r]-c[r]\[Rho][r]^5)};
]
PWr::usage="It contains: rRule, vRule (vierbeins), formsRules (applied more than once), X1X2Rule, c\[Rho]Rule1, c\[Rho]Rule2";

clearPWr:=Clear[vRule,formsRules,X1X2Rule,rRule, c\[Rho]Rule1, c\[Rho]Rule2];


PWc:=Module[{},
clearPWc;
cRule:={rc-> c,signOrientation-> signature * (-1) (* transformation of Levi-Civita*)};
prefactor[c_,\[Theta]_]:=(c X2[c,\[Theta]]X1[c,\[Theta]])^(1/8)/A[c]^(1/4);
vRule={vx-> Function[{c,\[Theta]},prefactor[c,\[Theta]]Sqrt[A[c]/(c^2-1)]],
vrc->Function[{c,\[Theta]},prefactor[c,\[Theta]] 1/(Sqrt[A[c]](c^2-1))], 
v\[Theta]-> Function[{c,\[Theta]},prefactor[c,\[Theta]] 1/Sqrt[c]],
v\[Phi]-> Function[{c,\[Theta]},prefactor[c,\[Theta]] 1/Sqrt[X2[c,\[Theta]]] Sin[\[Theta]]],
v1-> Function[{c,\[Theta]},prefactor[c,\[Theta]]Sqrt[A[c]/(c X2[c,\[Theta]])]Cos[\[Theta]]],
v2-> Function[{c,\[Theta]},prefactor[c,\[Theta]]Sqrt[A[c]/X1[c,\[Theta]]]Cos[\[Theta]]]};
formsRules={
b-> Function[{c,\[Theta]},(Sqrt[c X1[c,\[Theta]]]-Sqrt[X2[c,\[Theta]]])/(Sqrt[c X1[c,\[Theta]]]+Sqrt[X2[c,\[Theta]]])],
B-> Function[{c,\[Theta],\[Phi]},b[c,\[Theta]]E^(I 2\[Phi])],
f-> Function[{c,\[Theta]},1/Sqrt[1-b[c,\[Theta]]^2]],

\[Omega]->Function[{c,\[Theta]},(A[c] X1[c,\[Theta]])/(4 (-1+c^2)^2)],
a1->Function[{c,\[Theta]},-(Sqrt[c^2-1]/c)Cos[\[Theta]]],
a2->Function[{c,\[Theta]}, A[c] Sqrt[c^2-1]/X1[c,\[Theta]] Sin[\[Theta]]Cos[\[Theta]]^2],
a3->Function[{c,\[Theta]},-(Sqrt[c^2-1]/X2[c,\[Theta]])Sin[\[Theta]]Cos[\[Theta]]^2]
(* Note that I use: \[ScriptCapitalA]=\[ExponentialE]^(\[ImaginaryI] \[Phi])(-\[ImaginaryI] a1[c,\[Theta]]d[\[Theta]]\[Wedge]\[Sigma]1 + \[ImaginaryI] a2[c,\[Theta]] \[Sigma]2\[Wedge]\[Sigma]3 + a3[c,\[Theta]] \[Sigma]1\[Wedge]d[\[Phi]]) *)
};

X1X2Rule={
X1->Function[{c,\[Theta]},Cos[\[Theta]]^2+c A[c] Sin[\[Theta]]^2],
X2->Function[{c,\[Theta]},c Cos[\[Theta]]^2+A[c] Sin[\[Theta]]^2]
};

ARule={A'[c_]-> (2 (-1+c A[c]))/(-1+c^2),\!\(\*
TagBox[
StyleBox[
RowBox[{
RowBox[{"Derivative", "[", "2", "]"}], "[", "A", "]"}],
ShowSpecialCharacters->False,
ShowStringCharacters->True,
NumberMarks->True],
FullForm]\)[c_]-> (2 A[c])/(-1+c^2)};

explicitARule={A-> Function[c,c+(c^2-1) 1/2 Log[(c-1)/(c+1)]]};
]
PWc::usage="It contains: cRule, vRule (vierbeins), formsRules (applied more than once), X1X2Rule, ARule and explicitARule (A[c]=\[Rho][c\!\(\*SuperscriptBox[\(]\), \(6\)]\))";
clearPWc:=Clear[prefactor,vRule,formsRules,X1X2Rule,ARule,explicitARule,cRule];



